// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGmreKLTxs7UiBhVsPchsBVunFgHAK8dA',
    appId: '1:404355120377:web:7f12e22e0546004d9df628',
    messagingSenderId: '404355120377',
    projectId: 'hammlys',
    authDomain: 'hammlys.firebaseapp.com',
    storageBucket: 'hammlys.firebasestorage.app',
    measurementId: 'G-3HL207GNL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBATCfwB264M1txJ5vy2h3-om8tUbWzOV0',
    appId: '1:404355120377:android:496d093960cfacb59df628',
    messagingSenderId: '404355120377',
    projectId: 'hammlys',
    storageBucket: 'hammlys.firebasestorage.app',
  );



}